<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listTextSuiteFiles</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gUmVhZGluZyB0aGUgZm9sZGVyIGFuZCBnZXR0aW5nIFN0cmVhbS4KdHJ5IChTdHJlYW08UGF0
aD4gd2FsayA9IEZpbGVzLndhbGsoUGF0aHMuZ2V0KCIuL3BhY2thZ2VzIikpKSB7CgogICAgLy8g
RmlsdGVyaW5nIHRoZSBwYXRocyBieSBhIGZvbGRlciBhbmQgYWRkaW5nIGludG8gYSBsaXN0LgoK
ICAgIExpc3Q8U3RyaW5nPiBmaWxlTmFtZXNMaXN0ID0gd2Fsay5tYXAoeCAtPiB4LnRvU3RyaW5n
KCkpLmZpbHRlcihmIC0+IGYuY29udGFpbnMoIlRlc3RTdWl0ZS54bWwiKSkKICAgICAgICAgICAg
LmNvbGxlY3QoQ29sbGVjdG9ycy50b0xpc3QoKSk7CgogICAgLy8gcHJpbnRpbmcgdGhlIGZvbGRl
ciBuYW1lcwogICAgZmlsZU5hbWVzTGlzdC5mb3JFYWNoKFN5c3RlbS5vdXQ6OnByaW50bG4pOwoK
ICAgIElEYXRhQ3Vyc29yIGMgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKICAgIElEYXRhVXRpbC5w
dXQoYywgInRlc3RTdWl0ZXMiLCBmaWxlTmFtZXNMaXN0LnRvQXJyYXkobmV3IFN0cmluZ1tmaWxl
TmFtZXNMaXN0LnNpemUoKV0pKTsKICAgIGMuZGVzdHJveSgpOwp9IGNhdGNoIChJT0V4Y2VwdGlv
biBlKSB7CiAgICBlLnByaW50U3RhY2tUcmFjZSgpOwp9</value>
</Values>
