<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFileContents</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgYyA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgZm5hbWUgPSBJRGF0
YVV0aWwuZ2V0U3RyaW5nKGMsICJmaWxlbmFtZSIpOwoKaWYgKGZuYW1lID09IG51bGwpCgl0aHJv
dyBuZXcgU2VydmljZUV4Y2VwdGlvbigicHJvdmlkZSBmaWxlIG5hbWUgcGxlYXNlIik7CgovLyBw
cm9jZXNzCgpieXRlW10gZGF0YSA9IG51bGw7CnRyeSB7CglkYXRhID0gRmlsZXMucmVhZEFsbEJ5
dGVzKFBhdGhzLmdldChmbmFtZSkpOwoKfSBjYXRjaCAoRmlsZU5vdEZvdW5kRXhjZXB0aW9uIGUp
IHsKCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUpOwp9IGNhdGNoIChJT0V4Y2VwdGlvbiBl
KSB7Cgl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihlKTsKfQoJCi8vIHBpcGVsaW5lIG91dAoK
SURhdGFVdGlsLnB1dChjLCAic3RyaW5nIiwgbmV3IFN0cmluZyhkYXRhKSk7</value>
</Values>
